PrintComment: ThisGoesHere cleans up translations
MoveFolder:
- From: plugins/Krumpac-Krumpac_Reforge_Translations/Krumpac-Datys_Professions/translations
  To: plugins/Krumpac-Datys_Professions
# - From: plugins/Krumpac-Krumpac_Reforge_Translations/Krumpac-Krumpac_Armors/translations
#   To: plugins/Krumpac-Krumpac_Armors
# - From: plugins/Krumpac-Krumpac_Reforge_Translations/Krumpac-Krumpac_Building_Pieces/translations
#   To: plugins/Krumpac-Krumpac_Building_Pieces
# - From: plugins/Krumpac-Krumpac_Reforge_Translations/Krumpac-Krumpac_Reforge_Core/translations
#   To: plugins/Krumpac-Krumpac_Reforge_Core
# - From: plugins/Krumpac-Krumpac_Reforge_Translations/Krumpac-Krumpac_Sacrificing_Altars/translations
#   To: plugins/Krumpac-Krumpac_Sacrificing_Altars
# - From: plugins/Krumpac-Krumpac_Reforge_Translations/Krumpac-Krumpac_Weapon_Arsenal/translations
#   To: plugins/Krumpac-Krumpac_Weapon_Arsenal
- From: plugins/Krumpac-Krumpac_Reforge_Translations/Krumpac-Krumpac-Krump_Monsters_Pack_1/translations
  To: plugins/Krumpac-Krumpac-Krump_Monsters_Pack_1
# - From: plugins/Krumpac-Krumpac_Reforge_Translations/Krumpac-Krumpac_Dungeon_Meadows/translations
#   To: plugins/Krumpac-Krumpac_Dungeon_Meadows
DeleteFile:
- plugins/Krumpac-Krumpac_Sacrificing_Altars/translations/Krumpac_Tribe_Ornaments.Chinese.yml
- plugins/Krumpac-Krumpac_Sacrificing_Altars/translations/Krumpac_Tribe_Ornaments.English.yml
- plugins/Krumpac-Krumpac_Sacrificing_Altars/translations/Krumpac_Tribe_Ornaments.French.yml
- plugins/Krumpac-Krumpac_Sacrificing_Altars/translations/Krumpac_Tribe_Ornaments.German.yml
- plugins/Krumpac-Krumpac_Sacrificing_Altars/translations/Krumpac_Tribe_Ornaments.Korean.yml
- plugins/Krumpac-Krumpac_Sacrificing_Altars/translations/Krumpac_Tribe_Ornaments.Polish.yml
- plugins/Krumpac-Krumpac_Sacrificing_Altars/translations/Krumpac_Tribe_Ornaments.Russian.yml
- plugins/Krumpac-Krumpac_Sacrificing_Altars/translations/Krumpac_Tribe_Ornaments.Spanish.yml
- plugins/Krumpac-Krumpac_Sacrificing_Altars/translations/Krumpac_Tribe_Ornaments.Turkish.yml
- plugins/Krumpac-Krumpac_Sacrificing_Altars/translations/Krumpac_Tribe_Ornaments.Ukrainian.yml
