name: Zip Files

on:
  workflow_dispatch:

  # jobs:
  # zip-files:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: vimtor/action-zip@v1
  #     with:
  #       files: manifest.json README.md CHANGELOG.md icon.png config plugins
  #       dest: krumpac-translations.zip

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: 'release.zip'
        exclusions: '*.git* .yamllint'
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "release.zip"
        token: ${{ secrets.SOURCE_PUSH_TOKEN }}
